/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package superpuissance4_kaeppelin_védie;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author vedie
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    Joueur[] ListeJoueurs = new Joueur[2];
    Joueur joueurCourant;
    Grille GrilleJeu = new Grille();

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
        panneau_info_joueurs.setVisible(false);
        panneau_info_partie.setVisible(false);

        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {     
                CelluleGraphique CellGraph = new CelluleGraphique(GrilleJeu.CellulesJeu[i][j]);
                panneau_grille.add(CellGraph);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panneau_grille = new javax.swing.JPanel();
        panneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        nom_joueur1 = new javax.swing.JTextField();
        nom_joueur2 = new javax.swing.JTextField();
        panneau_info_joueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_j1_nom = new javax.swing.JLabel();
        lbl_j1_couleur = new javax.swing.JLabel();
        lbl_j1_desint = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_j2_nom1 = new javax.swing.JLabel();
        lbl_j2_couleur1 = new javax.swing.JLabel();
        lbl_j2_desint1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panneau_info_partie = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        message = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_col_6 = new javax.swing.JButton();
        btn_col_0 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 672, 576));

        panneau_creation_partie.setBackground(new java.awt.Color(204, 255, 204));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom joueur 2:");
        panneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setText("Nom joueur 1:");
        panneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btn_start.setText("Démarrer partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        nom_joueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur1ActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, -1));

        nom_joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur2ActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, -1));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 290, 120));

        panneau_info_joueurs.setBackground(new java.awt.Color(204, 255, 204));
        panneau_info_joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Infos joueurs");
        panneau_info_joueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel4.setText("Couleur :");
        panneau_info_joueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setText("Désintégrateurs:");
        panneau_info_joueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lbl_j1_nom.setText("nomJoueur1");
        panneau_info_joueurs.add(lbl_j1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        lbl_j1_couleur.setText("CouleurJoueur1");
        panneau_info_joueurs.add(lbl_j1_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        lbl_j1_desint.setText("nbDesintJoueur1");
        panneau_info_joueurs.add(lbl_j1_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel10.setText("joueur 1:");
        panneau_info_joueurs.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel6.setText("Couleur :");
        panneau_info_joueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel7.setText("Désintégrateurs:");
        panneau_info_joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lbl_j2_nom1.setText("nomJoueur2");
        panneau_info_joueurs.add(lbl_j2_nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        lbl_j2_couleur1.setText("CouleurJoueur2");
        panneau_info_joueurs.add(lbl_j2_couleur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        lbl_j2_desint1.setText("nbDesintJoueur2");
        panneau_info_joueurs.add(lbl_j2_desint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel11.setText("joueur 2:");
        panneau_info_joueurs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        panneau_info_joueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 20));

        getContentPane().add(panneau_info_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 290, 220));

        panneau_info_partie.setBackground(new java.awt.Color(204, 255, 204));
        panneau_info_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Infos jeu");
        panneau_info_partie.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        jLabel12.setText("joueur courant:");
        panneau_info_partie.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lbl_jcourant.setText("nomJoueur");
        panneau_info_partie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        message.setViewportView(jTextArea1);

        panneau_info_partie.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 270, 100));

        getContentPane().add(panneau_info_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 290, 210));

        btn_col_6.setText("7");
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 10, -1, -1));

        btn_col_0.setText("1");
        getContentPane().add(btn_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btn_col_1.setText("2");
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 10, -1, -1));

        btn_col_2.setText("3");
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 10, -1, -1));

        btn_col_3.setText("4");
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 10, -1, -1));

        btn_col_4.setText("5");
        btn_col_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, -1, -1));

        btn_col_5.setText("6");
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        setBounds(0, 0, 1044, 702);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void nom_joueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur1ActionPerformed

    private void nom_joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur2ActionPerformed

    private void btn_col_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col_4ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        panneau_info_joueurs.setVisible(true);
        panneau_info_partie.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint();   
        btn_start.setEnabled(false);

        
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }
    public void attribuerCouleursAuxJoueurs(){
    Random generateurAleat = new Random();
    int n = generateurAleat.nextInt(1);
    if (n!=1){
        ListeJoueurs[0].affecterCouleur("rouge");
        ListeJoueurs[1].affecterCouleur("jaune");
        System.out.println("la couleur du joueur1 est" +ListeJoueurs[0].Nom);
         System.out.println("la couleur du joueur2 est" +ListeJoueurs[1].Nom);
    }
    else {
        ListeJoueurs[0].affecterCouleur("jaune");
        ListeJoueurs[1].affecterCouleur("rouge");
        System.out.println("la couleur du joueur1 est" +ListeJoueurs[1].Nom);
        System.out.println("la couleur du joueur2 est" +ListeJoueurs[0].Nom);

    }  


    }
    public void initialiserPartie(){
           String NomJoueur1 = nom_joueur1.getText();
        Joueur J1 = new Joueur(NomJoueur1);
        
        String NomJoueur2 = nom_joueur2.getText();
        Joueur J2 = new Joueur(NomJoueur2);
        
        
        System.out.println(J1.Nom + "a la couleur "+ J1.Couleur);
        System.out.println(J2.Nom + "a la couleur "+ J2.Couleur);

        
        ListeJoueurs[0]=J1;
        ListeJoueurs[1]=J2;
        
                attribuerCouleursAuxJoueurs();    //Distribution des couleurs:

                
       lbl_j1_nom.setText(NomJoueur1);
       lbl_j2_nom1.setText(NomJoueur2);
       
       lbl_j1_couleur.setText(J1.Couleur);
       lbl_j2_couleur1.setText(J2.Couleur);

       lbl_j1_desint.setText(J1.nombreDesintegrateurs+ "");
       lbl_j2_desint1.setText(J2.nombreDesintegrateurs+"");

      
    //Création de la grille
    GrilleJeu.viderGrille();
    int nbTN=0;
    while (nbTN<=5){
        int ligne=(int)(Math.random() * 6);
        int colone=(int)(Math.random() * 7);
        if (GrilleJeu.CellulesJeu[ligne][colone].desintegrateur==false && GrilleJeu.CellulesJeu[ligne][colone].trouNoir==false){
            if (nbTN==4 || nbTN==5){
                GrilleJeu.placerTrouNoir(ligne,colone);
                GrilleJeu.placerDesintegrateur(ligne,colone);
            }else{
                GrilleJeu.placerTrouNoir(ligne,colone);
            }
            nbTN+=1;
    }
    }
    
       
    int nbDesint=0;
    while (nbDesint<=3){
        int ligne=(int)(Math.random() * 6);
        int colone=(int)(Math.random() * 7);
        if (GrilleJeu.CellulesJeu[ligne][colone].desintegrateur==false && GrilleJeu.CellulesJeu[ligne][colone].trouNoir==false){
            GrilleJeu.placerDesintegrateur(ligne,colone);
            nbDesint+=1;
        }else{
                nbDesint=nbDesint;
                }
    }    
    for (int i=0;i<21;i++){
        if (ListeJoueurs[0].Couleur.equals("R")){
            Jeton jetonjoueurR = new Jeton("R");
            ListeJoueurs[0].ajouterJeton(jetonjoueurR);
            Jeton jetonjoueurJ = new Jeton("J");
            ListeJoueurs[1].ajouterJeton(jetonjoueurJ);
        }else{
            Jeton jetonjoueurR = new Jeton("R");
            ListeJoueurs[1].ajouterJeton(jetonjoueurR);
            Jeton jetonjoueurJ = new Jeton("J");
            ListeJoueurs[0].ajouterJeton(jetonjoueurJ);
        }
    }
}
        
    public void debuterPartie(){
            //inscription des 2 joueurs:
     
        
        // premier joueur à commencer la partie 
        Random generateurAleat = new Random();
        int n = generateurAleat.nextInt(1);
        if (n!=1){
            joueurCourant = ListeJoueurs[0];
                                           
                       
        }
        else{
            joueurCourant = ListeJoueurs[1];
        }
                

        
        
        initialiserPartie();
        
        while(GrilleJeu.etreRemplie()==false/* =nombre de jetons pour le joueur(verifier)*/ && GrilleJeu.etreGagnantePourJoueur(ListeJoueurs[1])==false  /*partie finie?*/&&GrilleJeu.etreGagnantePourJoueur(ListeJoueurs[1])==false ){
            
            Scanner sc = new Scanner(System.in);
            System.out.println(joueurCourant.Nom + "c'est a vous de jouer ");
            System.out.println(joueurCourant.Nom + "il vous reste il faut aussi rajouter le nombre de désintégrateur");
            System.out.println("1) Placer un jeton");
            System.out.println("2) Récupérer un jeton");
            System.out.println("3) Utiliser un désintégrateur");
            int saisie = sc.nextInt();
            while (saisie>3 || saisie<=0){
                System.out.println("ERREUR!!!!: Veuillez ressaisir un chiffre compris entre 1 et 3:");
                saisie = sc.nextInt();
           
            }
            if (saisie==1){ 
                Scanner s = new Scanner(System.in);
                int Numcolonne = s.nextInt()-1;
                while(Numcolonne>6 && Numcolonne<0 ){
                    System.out.println("monsieur vous ne savez pas compter les colonnes, ressaisissez un numéro de colonne");
                    Numcolonne = s.nextInt()-1;
                    
                }    
                while (GrilleJeu.etreRemplie()==true){
                    System.out.println("la colonne est pleine, entrez a nouveau un nouveau numéro de colonne");
                    Numcolonne = s.nextInt()-1;
                }                    
                
            }
                
            joueurCourant.nombreJetonsRestants = joueurCourant.nombreJetonsRestants-1;
            System.out.println(joueurCourant.Nom + ", il vous reste"+ joueurCourant.nombreJetonsRestants);
                
                
                
                
                
            if (saisie==2){
                Scanner nbre = new Scanner(System.in);
                System.out.println("entrez votre numéro de ligne pour récuperer votre jeton");
                int ligne = nbre.nextInt();
                while (ligne<0 && ligne>5){
                    System.out.println("vous ne pouvez pas saisir un tel chiffre boloss");
                    ligne = nbre.nextInt()-1;
                }
                Scanner Nombre = new Scanner(System.in);
                int colonne = Nombre.nextInt();
                while (colonne <0 && colonne>6){
                    System.out.println("vous ne pouvez pas saisir un tel chiffre boloss");
                    colonne = nbre.nextInt()-1;                                                      
                }                
                if (GrilleJeu.celluleOccupee(ligne, colonne)==false && GrilleJeu.recupererJeton(ligne, colonne).Couleur.equals(joueurCourant.Couleur)){
                    GrilleJeu.tasserGrille(colonne);
                    joueurCourant.nombreJetonsRestants = joueurCourant.nombreJetonsRestants-1;
                    System.out.println(joueurCourant.Nom + ", il vous reste"+ joueurCourant.nombreJetonsRestants);                                       
                }
                              
            }                      
            
            if (saisie==3 && joueurCourant.nombreDesintegrateurs!=0){
                System.out.println("vous allez utiliser un désintégrateur");             
                Scanner nbre2 = new Scanner(System.in);
                System.out.println("entrez votre numéro de ligne pour récuperer votre jeton");
                int ligne = nbre2.nextInt();
                
                while (ligne<0 && ligne>5){
                    System.out.println("vous ne pouvez pas saisir un tel chiffre boloss");
                    ligne = nbre2.nextInt()-1;
                }
                Scanner Nombre2 = new Scanner(System.in);
                int colonne = Nombre2.nextInt();
                
                while (colonne <0 && colonne>6){
                    System.out.println("vous ne pouvez pas saisir un tel chiffre boloss");
                    colonne = Nombre2.nextInt()-1;        
               
                
            }
            if (saisie==3 && joueurCourant.nombreDesintegrateurs==0){
                System.out.println("ERREUR: Vous n'avez pas de désintégrateur à utiliser");
                System.out.println("Rechoississez ce que vous voulez faire: 1)Placer un jeton ou 2)Récupérer un jeton");
                saisie = sc.nextInt();
                while (saisie>2 || saisie<=0){
                    System.out.println("ERREUR: Veuillez ressaisir un choix compris entre 1 et 2:");
                    saisie = sc.nextInt();
                }
            }
            if (joueurCourant==ListeJoueurs[0]){
                joueurCourant=ListeJoueurs[1];
            }
            else{
                joueurCourant=ListeJoueurs[0];
            }

            }
            if(GrilleJeu.etreGagnantePourJoueur(ListeJoueurs[0])==true){
                System.out.println(ListeJoueurs[0].Nom+" a gagné'");  
            }
            
            if(GrilleJeu.etreGagnantePourJoueur(ListeJoueurs[1])==true){
                System.out.println(ListeJoueurs[1].Nom+" a gagné");
            }
            
            if(GrilleJeu.etreRemplie()==true){
                System.out.println("LA partie de termine, il n'y a pas de gagant--> égalité!");
            }
            
                
            
        }    
    
    
    
    
    
    } 
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_col_0;
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_j1_couleur;
    private javax.swing.JLabel lbl_j1_desint;
    private javax.swing.JLabel lbl_j1_nom;
    private javax.swing.JLabel lbl_j2_couleur1;
    private javax.swing.JLabel lbl_j2_desint1;
    private javax.swing.JLabel lbl_j2_nom1;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info_joueurs;
    private javax.swing.JPanel panneau_info_partie;
    // End of variables declaration//GEN-END:variables
}
